baseball = Sport.create(:name => 'Baseball', :abbr => 'BB')
mlb = baseball.levels.create(:name => 'Major League Baseball', :abbr => 'MLB', :major => true)
@nl = mlb.leagues.create(:name => 'National League', :abbr => 'NL')
@al = mlb.leagues.create(:name => 'American League', :abbr => 'AL')
#run this script on the live data to export to the following ruby format
#select distinct concat('@', lcase(mt_gd2mlb),' = @', lcase(ml_abbr), '.teams.create(:name => \'', mt_name, '\', :rotoworld_abbr => \'', mt_rotoworld, '\', :cbs_abbr => \'', mt_cbs,'\', :mlb_abbr => \'', mt_mlb,'\', :yahoo_abbr => \'', mt_yahoo,'\', :gd2mlb_abbr => \'', mt_gd2mlb,'\', :location => \'', mt_location,'\', :mlb_id => \'', mt_mlb_id,'\', :twitter_handle => \'', mt_twitter_handle,'\', :twitter_id => \'', mt_twitter_id,'\', :twitter_oauth_token => \'', mt_twitter_oauth_token,'\', :twitter_oauth_token_secret => \'', mt_twitter_oauth_token_secret,'\', :twitter_hash => \'', mt_hash,'\', :last_favorite => \'', mt_last_fav, '\')') rr from piker.mlbteams mt inner join piker.mlbleagues ml on ml_key = mt_ml_key where mt_ignore is null;
load 'db/seeds/secret_teams.rb'
#select concat(case when mt_key is null then 'Player' else concat('@', lcase(mt_gd2mlb), '.players') end, '.create(:first_name => \'', replace(pl_fName, '\'', '\\\''), '\', :last_name => \'', replace(pl_lName,'\'','\\\''), '\', :dob => ', ifnull(concat('\'',pl_dob,'\''), 'nil'),', :bats => \'', ifnull(pl_b,''),'\', :throws => \'', ifnull(pl_t,''),'\', :birthplace => \'', ifnull(replace(pl_birthplace,'\'','\\\''),''),'\', :school => \'', ifnull(replace(pl_school,'\'','\\\''),''),'\', :bbrefminors_id => \'', ifnull(pl_bbrefminors,''),'\', :mlb_id => \'', ifnull(pl_mlb,''),'\', :cbs_id => \'', ifnull(pl_cbs,''),'\', :msn_id => \'',  ifnull(pl_msn,''),'\', :rotoworld_id => \'', ifnull(pl_rotoworld,''),'\', :fangraphs_id => \'', ifnull(pl_fangraph,''),'\', :milb_id => \'', ifnull(pl_milb,''),'\', :yahoo_id => \'', ifnull(pl_yahoo,''),'\', :espn_id => \'', ifnull(pl_espn,''),'\', :bbref_id => \'', ifnull(replace(pl_bbref,'\'','\\\''),''),'\', :marcel_id => \'', ifnull(pl_marcel,''),'\', :played_today => \'', case when 1 then 'true' else 'false' end,'\', :duplicate_pl_key => ', ifnull(pl_duplicate_pl_key, 'nil'),', :espn_alt_id => \'', ifnull(pl_espn_alt,''),'\', :starting_today => ', case when 1 then 'true' else 'false' end,', :last_start => ', ifnull(concat('\'',pl_laststart,'\''),'nil'),', :last_appeared => ', ifnull(concat('\'',pl_lastappeared,'\''),'nil'),', :twitter_handle => ', ifnull(concat('\'',pl_twitter_handle,'\''),'nil'),', :contract_info => \'', ifnull(pl_freeagent, ''),'\', :pl_key => ', pl_key, ')') from piker.players left join piker.mlbteams on mt_key = pl_mt_key and mt_ignore is null;
load 'db/seeds/secret_players.rb'
