default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Puj#5ols
  pool: 5
 
development:
  <<: *default
  database: game_api_dev

test:
  <<: *default
  database: game_api_test