default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%=Rails.application.secrets[:password]%>
  pool: 5
 
development:
  <<: *default
  database: benchwarner_api_dev

test:
  <<: *default
  database: benchwarner_api_test